@startuml
Client -> AbstractAuthenticationProcessingFilter: post: login

AbstractAuthenticationProcessingFilter --> UsernamePasswordAuthenticationFilter: filter
UsernamePasswordAuthenticationFilter --> ProviderManager: getAuthenticationManager()
ProviderManager --> UserService: authenticate()
UserService --> ProviderManager: loadUserByUsername()
ProviderManager --> AbstractAuthenticationProcessingFilter: successfulAuthentication

AbstractAuthenticationProcessingFilter --> HeaderWriterFilter: writeHeaders()


@enduml



