@startuml
Client -> AuthorizationEndpoint: get: /oauth/authorize
AuthorizationEndpoint --> Client: login page

Client --> SpringLogin: custom: /authentication/login
SpringLogin --> AuthorizationEndpoint: get: /oauth/authorize
AuthorizationEndpoint --> WhitelabelApprovalEndpoint: get: /oauth/confirm_access
WhitelabelApprovalEndpoint --> Client: confirm page

Client --> AuthorizationEndpoint: post: /oauth/authorize
AuthorizationEndpoint --> Client: redirect: authorize code

Client -> TokenEndpoint: post: /oauth/token
TokenEndpoint --> Client: Response: token
@enduml



