spring:
  application:
    name: ms-authorization
  thymeleaf:
    prefix: classpath:/views/
    suffix: .html
    cache: false
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:3306/oauth2?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    hikari:
      minimum-idle: 3
      idle-timeout: 600000
      maximum-pool-size: 15
      auto-commit: true
      pool-name: DB-HikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  liquibase:
    enabled: true
    change-log: classpath:/changelog/changelog-master.xml


mybatis-plus:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  # 实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.sailfish.authorization.model.*
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      idType: AUTO
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

server:
  port: 8762
  tomcat:
    uri-encoding: UTF-8
    maxHttpPostSize: 4194304
    maxHttpHeaderSize: 65536
  maxHttpHeaderSize: 65536
  maxHttpPostSize: 4194304
